name: stack-macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: haskell-actions/setup@v2.7.1
      with:
        ghc-version: '9.6.5'
        enable-stack: true
        stack-version: 'latest'
    - name: Setup tool-chains
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install libomp || true
        pip3 install pyyaml || true
        ## Stack is preinstalled on the GHA runners
        #wget -qO- https://get.haskellstack.org/ | sed -e 's/^STACK_VERSION=.*/STACK_VERSION="1.9.3"/g' | sh || true
        #wget -qO- https://get.haskellstack.org/ | sh || true
        clang --version
        stack --version
        brew tap hasktorch/libtorch-prebuild https://github.com/hasktorch/homebrew-libtorch-prebuild || true
        brew install libtorch-prebuild@2.3 || true
        brew tap hasktorch/tokenizers https://github.com/hasktorch/tokenizers || true
        brew install libtokenizers || true
        echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:/opt/homebrew/opt/libomp/lib:$DYLD_LIBRARY_PATH" >> "${GITHUB_ENV}"
        #pushd deps/ ; ./get-deps.sh -a cpu -c ;popd
    - name: Cache .stack
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: "\
          ${{ runner.os }}-stack\
          -${{ hashFiles('**/stack.yaml.lock') }}\
          -${{ hashFiles('**/package.yaml') }}\
        "
        restore-keys: |
          ${{ runner.os }}-stack-
    - name: Build
      run: |
        #. setenv
        stack build --stack-yaml stack-macos.yaml entropy || true
        stack build --stack-yaml stack-macos.yaml \
          libtorch-ffi \
          libtorch-ffi-helper \
          hasktorch \
          codegen \
          examples \
          bounding-box \
          dataloader-cifar10 \
          untyped-nlp
    - name: Test
      run: |
        #. setenv
        stack test --stack-yaml stack-macos.yaml codegen
        stack test --stack-yaml stack-macos.yaml libtorch-ffi
        stack test --stack-yaml stack-macos.yaml hasktorch
        stack exec --stack-yaml stack-macos.yaml codegen-exe
        stack exec --stack-yaml stack-macos.yaml xor-mlp
        stack exec --stack-yaml stack-macos.yaml regression
        stack exec --stack-yaml stack-macos.yaml gaussian-process
        stack exec --stack-yaml stack-macos.yaml vae
        stack exec --stack-yaml stack-macos.yaml optimizers
